rest:
  url: "https://example.org/primenumbers/v1"
  port: 8443
  prueba:
    - env:
        - name: Java
          value: 128 mb
        - name: Key
          value: access.aws
      env2:
        - configmapRef:
            name: Python
        - secretRef:
            name: queli
# prime_numbers: [2, 3, 5, 7, 11, 13, 17, 19]
